# Generated by Django 4.2.11 on 2025-01-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Views', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulation',
            name='time',
        ),
        migrations.RemoveField(
            model_name='navitem',
            name='time',
        ),
        migrations.AddField(
            model_name='formulation',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='formulation',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
