# Generated by Django 4.2.11 on 2025-01-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Views', '0002_remove_formulation_time_remove_navitem_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulation',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
